x-name: daedalus_um

services:
  app:
    build: ./app
    image: um-app:latest
    container_name: um-app
    restart: "no"
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
    volumes:
      - ./broadcaster/service:/service/service
      - broadcast_volume:/data/broadcast_volume
    environment:
      MCAST_PORT: "40085"
      MCAST_IP: "238.1.1.95"
      UPDATE_FILE_PATH : "/data/broadcast_volume"
    networks:
      outside-net:
        ipv4_address: 172.30.0.10

networks:
  outside-net:
    external: true
    name: outside-net

volumes:
  broadcast_volume: