x-name: daedalus_um

services:
  mongo:
    image: mongo:6.0
    command: mongod --quiet --logpath /data/db/mongod.log --logappend
    container_name: um-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - um-internal

  backend:
    build: ./backend
    image: um-backend:latest
    container_name: um-backend
    restart: "no"
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/tmp:/tmp
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/um-db"
      NA_IPS: "172.20.0.2,172.21.0.2"
      UDP_PORT: 5000
    networks:
      default:
      um-internal:
      netA:
        ipv4_address: 172.20.0.2
      netB:
        ipv4_address: 172.21.0.2



networks:
  default:
    driver: bridge

  um-internal:
    driver: bridge

  netA:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

  netB:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

volumes:
  mongo_data: