version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: infra_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: infra_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # ADD THIS LINE: It auto-runs your SQL file on startup
      - app/database.sql:/docker-entrypoint-initdb.d/init.sql 

  adminer:
    image: python:3.12-slim
    container_name: backend_adminer
    ports:
      - "9645:9645"
    
    depends_on:
      - db

volumes:
  mysql_data: