
services:
  mongo-isolated:
    image: mongo:7
    container_name: mongo-isolated
    restart: unless-stopped
    ports:
      - "${MONGO_ISOLATED_PORT}:27017"
    volumes:
      - mongo-isolated-data:/data/db
    networks:
      isolated-net:
        ipv4_address: 192.168.50.5
    command: mongod --quiet --logpath /dev/null --wiredTigerCacheSizeGB=1 --replSet=rs0 --bind_ip_all
    logging:
      driver: "none"  
    healthcheck:
      test: |
        mongosh --port 27017 --quiet --eval '
        try {
          rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongo-isolated:27017"}]});
        } catch (e) {}
        if (db.hello().isWritablePrimary) { quit(0) } else { quit(1) }
        '
      interval: 1s 
      timeout: 10s
      retries: 60
      start_period: 0s
      
  distributor:
    build: ${DISTRIBUTOR_PATH}
    image: distributor:latest
    container_name: distributor
    restart: "no"
    depends_on:
      mongo-isolated:
        condition: service_healthy
    ports:
      - "${DISTRIBUTOR_PORT}:11080"
    volumes:
      - store_volume:${STORE_PATH}:ro
      - ${DISTRIBUTOR_PATH}/service:/service/service
    env_file: 
      - .env
    networks:
      isolated-net:
        ipv4_address: 192.168.50.4

  store-manager:
    build: ${STORE_MANAGER_PATH}
    image: store-manager:latest
    container_name: store-manager
    restart: "no"
    depends_on:
      mongo-isolated:
        condition: service_healthy
    ports:
      - "${FLUTE_PORT}:${FLUTE_PORT}/udp"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - updates_volume:${UPDATES_PATH}
      - store_volume:${STORE_PATH}
      - ${STORE_MANAGER_PATH}/service:/service/service
    env_file:
      - .env
    environment:
      OUTPUT_PATH: ${UPDATES_PATH}
      DISTRIBUTOR_URL: http://distributor:${DISTRIBUTOR_PORT}
      FLUTE_PORT: ${FLUTE_PORT}
      FLUTE_IP: ${MULTICAST_IP}
    networks:
      mcast-gateway:
          ipv4_address: 172.30.1.3
      isolated-net:
          ipv4_address: 192.168.50.3
    sysctls:
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.default.rp_filter=0

  mongo-view:
    image: mongo:7
    container_name: mongo-view
    restart: unless-stopped
    ports:
      - "37017:27017"
    volumes:
      - mongo-view-data:/data/db
    command: mongod --wiredTigerCacheSizeGB=0.25 --quiet --logpath /dev/null
    logging:
      driver: "none"
    networks:
      view-net:
        ipv4_address: 172.30.2.4

  sys-view:
    build: ${VIEW_PATH}
    image: sys-view:latest
    container_name: sys-view
    restart: "no"
    ports:
      - "${VIEW_APP_PORT}:9090"   
      - "${VIEW_UDP_PORT}:5005/udp"                      
    volumes:
      - ${VIEW_PATH}:/service
    environment:
      - MONGO_URI=mongodb://mongo-view:27017
    depends_on:
      - mongo-view
    networks:
      view-net:
        ipv4_address: ${VIEW_IP}


networks:
  isolated-net:
    external: true
    name: isolated-net

  mcast-gateway:
    external: true
    name: mcast-gateway

  view-net:
    external: true
    name: view-net

volumes:
  mongo-isolated-data:
  mongo-view-data:
  updates_volume:
  store_volume:
