FROM gcc:12

RUN apt-get update && apt-get install -y \
    git \
    tcpdump \
    iproute2 \
    curl \
    build-essential \
    cmake \
    ninja-build \
    libboost-system-dev \
    libnl-3-dev \
    libnl-genl-3-dev \
    libspdlog-dev \
    libtinyxml2-dev \
    libconfig++-dev \
    clang-tidy \
    clang \
    libssl-dev \
    nlohmann-json3-dev \
    libarchive-dev \
    libstdc++-12-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

# Clone & Install Mongo C Driver (Required Dependency)
RUN git clone --depth 1 --branch 1.29.0 https://github.com/mongodb/mongo-c-driver.git \
    && cd mongo-c-driver \
    && mkdir cmake-build && cd cmake-build \
    && cmake -G Ninja -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_BUILD_TYPE=Release .. \
    && cmake --build . --target install \
    && cd /tmp && rm -rf mongo-c-driver

# Clone & Install Mongo C++ Driver
RUN git clone --depth 1 --branch r4.0.0 https://github.com/mongodb/mongo-cxx-driver.git \
    && cd mongo-cxx-driver \
    && mkdir cmake-build && cd cmake-build \
    && cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DBUILD_ONLY_CXX_DRIVER=ON .. \
    && cmake --build . --target install \
    && cd /tmp && rm -rf mongo-cxx-driver

# Refresh system libs
RUN ldconfig

WORKDIR /service

# Clone rt-libflute library directly into service workspace
RUN mkdir -p deps && git clone https://github.com/5G-MAG/rt-libflute.git deps/rt-libflute

# Build flute first with GCC (the default toolchain in this image)
RUN cd deps/rt-libflute \
    && CC=gcc CXX=g++ cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF \
    && cmake --build build

COPY service/ .

# Force CMake to use clang & clang++ 
RUN CC=clang CXX=clang++ cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release \
    && cmake --build build

RUN cp build/StoreManager /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/StoreManager"]