
x-common-env: &common-env
  STORE_PATH: ${STORE_PATH}
  MONGO_URI: ${MONGO_URI}
  MONGO_PACKAGES_DB: ${MONGO_PACKAGES_DB}
  MONGO_PACKAGES_COLLECTION: ${MONGO_PACKAGES_COLLECTION}

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - isolated-net
    command: mongod --wiredTigerCacheSizeGB=0.25 --quiet --logpath /dev/null
    logging:
      driver: "none"

  distributor:
    build: ./distributor
    image: distributor:latest
    container_name: distributor
    restart: "no"
    ports:
      - "${DISTRIBUTOR_PORT}:11080"
    volumes:
      - store_volume:${STORE_PATH}:ro
      - ./distributor/service:/service/service
    environment:
      <<: *common-env
    networks:
      isolated-net:
        ipv4_address: 192.168.50.4

  store-manager:
    build: ./store-manager
    image: store-manager:latest
    container_name: store-manager
    restart: "no"
    ports:
      - "${FLUTE_PORT}:${FLUTE_PORT}/udp"
    cap_add:
      - NET_ADMIN
    volumes:
      - updates_volume:${UPDATES_PATH}
      - store_volume:${STORE_PATH}
      - ./store-manager/service:/service/service
    environment:
      <<: *common-env
      OUTPUT_PATH: ${UPDATES_PATH}
      DISTRIBUTOR_URL: http://distributor:${DISTRIBUTOR_PORT}
      UPDATE_FILE_REQUEST: ${UPDATE_FILE_REQUEST}
      FLUTE_PORT: ${FLUTE_PORT}
      IP: ${MULTICAST_IP}
    networks:
      - isolated-net
      - mcast-gateway
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'

  mcast-fwdr:
    build: ./mcast-fwdr
    image: mcast-fwdr:latest
    container_name: mcast-fwdr
    cap_add:
      - NET_ADMIN
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
    networks:
      um-net:
        ipv4_address: 172.30.0.254
      mcast-gateway:
        ipv4_address: 172.30.1.2

networks:
  mcast-gateway:
    name: mcast-gateway
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.1.0/29

  isolated-net:
    name: network_isolated
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-isolated
    ipam:
      config:
        - subnet: 192.168.50.0/24
          gateway: 192.168.50.1

  um-net:
    external: true
    name: network_um

volumes:
  mongo_data:
  updates_volume:
  store_volume:
